-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg38ThKr25lnu6OaZE
FV1dnEwUJA8HNqHGlKS3OHyLLUKgCgYIKoZIzj0DAQehRANCAAQLjSRFAewcTl0i
9bQTVGMH/vE5eZSGGx+4bqyHvpwv9CKorEyHvH2qlWb7mIJ95hyIPcrHmj8ryAcd
pMmFhaDA
-----END PRIVATE KEY-----